Major Overhaul
tomsom/yoga-linux pull request #16
Opened 2022-12-05 20:59 UTC by Okazakee

Deleted useless redundant stuff and obsolete notations, better layout even for future changes, there is other room for improvements.

2022-12-05 22:53 UTC, imsofi requested changes
Lets not delete history here. This has become a core resource to find out what things are and were problems, how those issues were fixed, and any of their statuses plus further fixes.

Also most of the things you have deleted are still relevant issues, all without upstream patches? Like the USB-C dock is not up-streamed, and likely will not be fixed until 6.2. S4 sleep is still relevant, "the speakers suck" is still relevant, screen rotation is not yet up-streamed and has no ETA, S3 sleep is still relevant. I can go on but i think the general idea comes across.

2022-12-05 23:01 UTC, tomsom commented
Neat! Thank you :))

2022-12-05 23:02 UTC, merged

2022-12-05 23:06 UTC, imsofi reviewed
Added some comments on places that need some rewording, overall good once those are changed up. :+1:

2022-12-05 23:06 UTC, imsofi commented on README.md
> + > - [x] **Fixed incompatibility with 'Delock' USB-C dock**
This is not yet fixed, see #13

2022-12-05 23:06 UTC, imsofi commented on README.md
> + > - [x] **Fixed incompatibility with 'Delock' USB-C dock**
Will likely only get properly fixed in 6.2, some docks can still work under 6.1.

2022-12-05 23:06 UTC, imsofi commented on README.md
> + > - Seems to be working with the driver from this [Copr repo](https://copr.fedorainfracloud.org/coprs/d-k-bo/libfprint-goodixtls/).
This is still heavy WIP, not stable, and not cross platform. Should probably be put into a "Workaround" section to show the significance of not being a proper fix yet.

2022-12-05 23:07 UTC, imsofi commented
Ah shoot this got merged while i reviewed, guess we should get these issues into a new PR. :sweat_smile:

2022-12-05 23:13 UTC, tomsom commented
I don't have a model with a fingerprint reader so id be cool if you peeps can test what works and what not..

2022-12-05 23:43 UTC, Myaats commented
Might be worth adding a disclaimer for the BG5 firmware issue on models that use the BG5 SSD instead of Samsung, Micron or WD that permanently bricks unless they are updated to the newest firmware (0107ANLS) through Windows Update (It is not available through fwupd).

2022-12-06 00:00 UTC, tomsom commented
@Myaats Oh yes, should have added this a long time ago :o
Thank you for the reminder!

2022-12-06 00:12 UTC, Okazakee commented
Been a pleasure